# Generated by Django 5.1.4 on 2025-02-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_alter_usermodel_options_remove_usermodel_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='groups',
            field=models.ManyToManyField(blank=True, to='auth.group'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, to='auth.permission'),
        ),
    ]
